### ISSUE TITLE
Import from EPD data with excel file

### ISSUE THREAD

**Issue by Stoehrift** [GreenDelta/epd-editor#38]
There are problems by the import of exel files. There isn´t always the same structure in the export file. So it´s difficult to use templates to import the LCA data.

**Comment by msrocka** [comment]
@Stoehrift do you have an Example Excel file where the import does not work? The EPD profile `EN 15804` is selected as EPD profile of the data set, right?

The structure of the Excel file is very simple:
* Colum `A`: The label of the EPD module
* Colum `B`: The (optional) name of a scenario
* Column `C`: The **name** of the indicator (as defined in the EPD profile that is set as the profile of the data set)
* Column `D`: The indicator amount
* Column `E`: The indicator unit

So, indicators are identified by their name as defined in the EPD profile (you can check the names when you open the EPD profile). Note that these names are dependent on the respective data set language that is selected in the editor settings ( [attached is an example Excel file](https://github.com/GreenDelta/epd-editor/files/2282493/results.xlsx) that can be imported when the data set language is set to German).

To support multiple languages in the import, we could extend the import so that it searches for indicator names over all languages in the indicator data sets that are referenced by the respective EPD profile (this works only if the data sets are stored locally). @okworx What do you think?

**Comment by Stoehrift** [comment]
@msrocka thanks for the answer.
I get two versions of excel export. In results there is ADPE first issue and in results2 CRU is first. I exported it with the same programm and the same settings.
And even if we filter A-Z in colum A there is not the same structure in the document. So it´s difficult to prepare a master document to import.
[results.xlsx](https://github.com/GreenDelta/epd-editor/files/2282764/results.xlsx)
[results2.xlsx](https://github.com/GreenDelta/epd-editor/files/2282765/results2.xlsx)

**Comment by msrocka** [comment]
@Stoehrift The order of the rows is not important for the import. So, you can define your own order of modules and indicators in your import template. In your examples the modules are different in both files, e.g. the `results.xlsx` file has a `B1` module, the `results2.xlsx` module has not (which results in a different number of rows). Is this what you mean with `structure`?

I could import both files with the current version without errors. Or have I overseen something?
